#!/usr/bin/env bash
# acp-office supervision installer — keeps the office dashboard alive.
#
# Pattern from services/acp_supervision (workstream B), trimmed for a
# local app:
#   1. control wrapper   $PREFIX/bin/acp-office {start|stop|restart|status}
#      - start is idempotent: a live pidfile is a safe no-op
#      - the office server is a plain python process; the wrapper records
#        its pidfile (--pid-file) and never echoes $! into it
#   2. keepalive          $PREFIX/bin/acp-office-keepalive — called every
#      minute from cron; idempotently starts the office server (no-op when
#      alive). Also starts the cloudflared tunnel ONLY when the tunnel
#      credentials file already exists (~/.cloudflared/office.json);
#      without credentials it logs "tunnel not configured" and does
#      nothing (see docs/OFFICE.md for the one-time tunnel setup).
#   3. cron               a 1-minute cron line, tagged so reinstalls never
#      duplicate it
#
# Usage:
#   bash apps/acp_office/supervision/install.sh [--prefix DIR] [--port N]
#       [--python PATH] [--skip-cron] [--no-start] [--dry-run]
#
# Idempotent: safe to re-run. No identity, state, or databases are touched.
# Test seam: ACP_OFFICE_FAKE_CRONTAB=/path/to/file makes the cron
# installer read/write that file instead of the real crontab.
set -euo pipefail

CRON_MARKER="acp-office-keepalive"
PREFIX="${ACP_HOME:-$HOME/.acp}"
PORT="18081"
PYTHON=""
INSTALL_CRON=1
DO_START=1
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2;;
    --port) PORT="$2"; shift 2;;
    --python) PYTHON="$2"; shift 2;;
    --skip-cron) INSTALL_CRON=0; shift;;
    --no-start) DO_START=0; shift;;
    --dry-run) DRY_RUN=1; shift;;
    -h|--help) sed -n '2,32p' "$0"; exit 0;;
    *) echo "unknown option: $1" >&2; exit 1;;
  esac
done

[ -n "$PYTHON" ] || PYTHON="$(command -v python3)"

# --- repo location -------------------------------------------------------
PKG_DIR="$(cd "$(dirname "$0")" && pwd)"
case "$PKG_DIR" in
  */apps/acp_office/supervision)
    REPO_DIR="$(cd "$PKG_DIR/../../.." && pwd)"
    APP_MAIN="$REPO_DIR/apps/acp_office/__main__.py";;
  *)
    REPO_DIR=""
    APP_MAIN="$(cd "$PKG_DIR/.." && pwd)/__main__.py";;
esac
[ -f "$APP_MAIN" ] || { echo "acp-office: cannot find app at $APP_MAIN" >&2; exit 1; }

say() { echo "acp-office: $*"; }
run() { if [ "$DRY_RUN" = 1 ]; then echo "  [dry-run] $*"; else "$@"; fi; }

BIN_DIR="$PREFIX/bin"
RUN_DIR="$PREFIX/run"
LOG_DIR="$PREFIX/log"
mkdir -p "$BIN_DIR" "$RUN_DIR" "$LOG_DIR"
PID_FILE="$RUN_DIR/acp-office.pid"
LOG_FILE="$LOG_DIR/acp-office.log"
KEEPALIVE="$BIN_DIR/acp-office-keepalive"
WRAPPER="$BIN_DIR/acp-office"

# --- control wrapper -----------------------------------------------------
say "writing $WRAPPER"
if [ "$DRY_RUN" = 1 ]; then echo "  [dry-run] write $WRAPPER"; else
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# acp-office control wrapper (generated by acp_office supervision installer).
set -euo pipefail
PID_FILE="$PID_FILE"
LOG_FILE="$LOG_FILE"
APP_MAIN="$APP_MAIN"
PORT="$PORT"
PYTHON="$PYTHON"

alive() { [ -f "\$PID_FILE" ] && kill -0 "\$(cat "\$PID_FILE" 2>/dev/null)" 2>/dev/null; }

case "\${1:-}" in
  start)
    if alive; then echo "acp-office: already running (pid \$(cat \$PID_FILE))"; exit 0; fi
    rm -f "\$PID_FILE"
    # token: ACP_OFFICE_TOKEN env, else the server generates one and prints it to the log
    TOKEN_ARGS=""
    [ -n "\${ACP_OFFICE_TOKEN:-}" ] && TOKEN_ARGS="--token \$ACP_OFFICE_TOKEN"
    cd "$(dirname "$APP_MAIN")/.." || exit 1
    # shellcheck disable=SC2086
    nohup "\$PYTHON" -u "$APP_MAIN" --host 127.0.0.1 --port "\$PORT" \$TOKEN_ARGS >>"\$LOG_FILE" 2>&1 &
    echo "acp-office: starting (see \$LOG_FILE for the API token)"
    for i in 1 2 3 4 5 6 7 8 9 10; do
      sleep 1
      if curl -s -o /dev/null "http://127.0.0.1:\$PORT/"; then
        PID="\$(pgrep -f "[a]cp_office/__main__[.]py" | head -1)"
        [ -n "\$PID" ] && echo "\$PID" > "\$PID_FILE"
        echo "acp-office: up on http://127.0.0.1:\$PORT/"
        exit 0
      fi
    done
    echo "acp-office: failed to start; check \$LOG_FILE" >&2; exit 1
    ;;
  stop)
    if alive; then kill "\$(cat \$PID_FILE)"; echo "acp-office: stopped"; else echo "acp-office: not running"; fi
    rm -f "\$PID_FILE"
    ;;
  restart) "\$0" stop; sleep 1; "\$0" start;;
  status)
    if alive; then echo "acp-office: running (pid \$(cat \$PID_FILE), port \$PORT)"; else echo "acp-office: not running"; fi
    ;;
  *) echo "usage: acp-office {start|stop|restart|status}" >&2; exit 1;;
esac
EOF
chmod +x "$WRAPPER"
fi

# --- keepalive ------------------------------------------------------------
say "writing $KEEPALIVE"
if [ "$DRY_RUN" = 1 ]; then echo "  [dry-run] write $KEEPALIVE"; else
cat > "$KEEPALIVE" <<'KEEPEOF'
#!/usr/bin/env bash
# acp-office keepalive: idempotently start the office server (and the
# cloudflared tunnel, once its credentials exist). Called every minute
# from cron.
set -uo pipefail
PREFIX="${ACP_HOME:-$HOME/.acp}"
WRAPPER="$PREFIX/bin/acp-office"
LOG="$PREFIX/log/acp-office-keepalive.log"
ts() { date '+%F %T %Z'; }

# 1) office server
"$WRAPPER" status >/dev/null 2>&1 || true
if ! "$WRAPPER" status 2>/dev/null | grep -q running; then
  echo "$(ts) office down -> starting" >>"$LOG"
  "$WRAPPER" start >>"$LOG" 2>&1 || echo "$(ts) office start FAILED" >>"$LOG"
fi

# 2) cloudflared tunnel — only when its credentials file already exists.
#    The credentials file is created by the one-time tunnel setup in
#    docs/OFFICE.md (needs the user's Cloudflare token); without it this
#    section is a no-op by design.
CREDS="$HOME/.cloudflared/office.json"
if [ -f "$CREDS" ] && command -v cloudflared >/dev/null 2>&1; then
  if ! pgrep -f "[c]loudflared tunnel.*office[.]yml" >/dev/null 2>&1; then
    echo "$(ts) tunnel down -> starting" >>"$LOG"
    nohup cloudflared tunnel --config "$HOME/.cloudflared/office.yml" run office \
      >>"$PREFIX/log/acp-office-tunnel.log" 2>&1 &
  fi
elif [ ! -f "$CREDS" ]; then
  : # tunnel not configured yet; see docs/OFFICE.md
fi
KEEPEOF
chmod +x "$KEEPALIVE"
fi

# --- cron -----------------------------------------------------------------
# Host crontab is absent on this machine; supervision cron lines are
# registered as runtime cron jobs instead (see docs/OFFICE.md). The
# installer still writes the keepalive script; the runtime job
# `acp-office-keepalive` (created separately) calls it every minute.
if [ "$INSTALL_CRON" = 1 ]; then
  if command -v crontab >/dev/null 2>&1; then
    CRON_FILE="${ACP_OFFICE_FAKE_CRONTAB:-}"
    if [ -z "$CRON_FILE" ]; then
      existing="$(crontab -l 2>/dev/null || true)"
    else
      existing="$(cat "$CRON_FILE" 2>/dev/null || true)"
    fi
    if echo "$existing" | grep -q "$CRON_MARKER"; then
      say "cron line already present ($CRON_MARKER); skipping"
    else
      line="* * * * * $KEEPALIVE # $CRON_MARKER"
      say "installing cron: $line"
      if [ -n "$CRON_FILE" ]; then
        run bash -c "printf '%s\n%s\n' \"\$existing\" \"$line\" > \"$CRON_FILE\""
      else
        if [ "$DRY_RUN" = 1 ]; then
          echo "  [dry-run] (crontab -l; echo \"$line\") | crontab -"
        else
          (crontab -l 2>/dev/null; echo "$line") | crontab -
        fi
      fi
    fi
  else
    say "no host crontab: supervision is via the runtime cron job"
    say "  'acp-office-keepalive' (interval 1m), which calls $KEEPALIVE"
    say "  create it with the cron tools; see docs/OFFICE.md"
  fi
else
  say "cron install skipped (--skip-cron)"
fi

# --- start -----------------------------------------------------------------
if [ "$DO_START" = 1 ]; then
  say "starting office server"
  run "$WRAPPER" start
else
  say "start skipped (--no-start); run: $WRAPPER start"
fi

say "done. status: $WRAPPER status"
